## to run on H100
batch_size = 1024
micro_batch_size = 2
rollouts_per_example = 16
seq_len = 8192
mask_truncated_completions = false

[model]
name = "Qwen/Qwen3-4B-Instruct-2507"

[sampling]
max_tokens = 8192


[environment]
id = "deepcoder-minimal-edit"
args = { env_type = "both" }

[wandb.log_extras]
interval = 10

[eval]

[ckpt]
interval = 200 